apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: >-
      [{"apiVersion":"interconnectedcloud.github.io/v1alpha1",
        "kind":"Qdrouterd",
        "metadata":{
          "name":"amq-interconnect"
         },
        "spec":{
          "deploymentPlan": {
            "role":"interior",
            "size":2,
            "placement":"Any",
            "image":"quay.io/interconnectedcloud/qdrouterd:1.6.0"
          }
        }}]
    capabilities: Basic Install
    categories: Messaging
  name: qdrouterd-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - version: v1alpha1
      kind: Qdrouterd
      description: An instance of Qdrouterd
      displayName: Qdrouterd
      name: qdrouterds.interconnectedcloud.github.io
      resources:
      - kind: Service
        version: v1
      - kind: Deployment
        version: v1
      - kind: ServiceAccount
        version: v1
      - kind: qdrouterds
        version: v1alpha1
      - kind: rolebindings
        version: v1
      - kind: pods
        version: v1
      - kind: configmaps
        version: v1
      - kind: roles
        version: v1
      - kind: routes
        version: v1
      - kind: secrets
        version: v1
      specDescriptors:
      - description: The role and placement plan for the qdrouterd deployment
        displayName: DeploymentPlan
        path: deploymentPlan
      - description: Listeners for incoming connections to the router
        displayName: Listeners
        path: listeners
      - description: Listeners for inter router mesh connections
        displayName: InterRouterListeners
        path: interRouterListeners
      - description: Listeners for edge downlink connections
        displayName: EdgeListeners
        path: edgeListeners
      - description: TLS/SSL configuration for connections
        displayName: SslProfiles
        path: sslProfiles
      - description: Address configuration for distribution and phasing
        displayName: Addresses
        path: addresses
      - description: Auto links address configuration
        displayName: AutLinks
        path: autoLinks
      - description: Link routes address configuration
        displayName: LinkRoutes
        path: linkRoutes
      - description: Outbound client connections to AMQP 1.0 entity
        displayName: Connectors
        path: connectors
      - description: Outbound interior router connections for mesh operation
        displayName: InterRouterConnectors
        path: interRouterConnectors
      - description: Outbound edge router connections for edge uplink
        displayName: EdgeConnectors
        path: edgeConnectors
      statusDescriptors:
      - description: The current revision of the qdrouterd cluster
        displayName: Revision Number
        path: revNumber
      - description: The current pods
        displayName: Pods
        path: pods
      - description: The current conditions
        displayName: Conditions
        path: conditions
  description: |
    The qdr Operator creates and maintains interior mesh or edge
    deployments on kubernetes and OpenShift.
  displayName: Qdrouterd Operator
  install:
    spec:
      deployments:
      - name: qdrouterd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: qdrouterd-operator
          template:
            metadata:
              labels:
                name: qdrouterd-operator
            spec:
              serviceAccountName: qdrouterd-operator
              containers:
              - command:
                - qdrouterd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: qdrouterd-operator
                image: quay.io/myeung/qdrouterd-operator
                imagePullPolicy: Always
                name: qdrouterd-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - serviceaccounts
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - "route.openshift.io"
          resources:
          - routes
          - routes/custom-host
          - routes/status
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - "certmanager.k8s.io"
          resources:
          - issuers
          - certificates
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - interconnectedcloud.github.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: qdrouterd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.1.0
